export const USER_LOGGED_IN = "USER_LOGGED_IN";
export const USER_LOGGED_OUT = "USER_LOGGED_OUT";

export const API_USER_DATA_REQUEST = "API_USER_DATA_REQUEST";
export const API_USER_DATA_SUCCESS = "API_USER_DATA_SUCCESS";
export const API_USER_DATA_FAILED = "API_USER_DATA_FAILED";

export const API_ADDRESS_DATA_REQUEST = "API_ADDRESS_DATA_REQUEST";
export const API_ADDRESS_DATA_SUCCESS = "API_ADDRESS_DATA_SUCCESS";
export const API_ADDRESS_DATA_FAILED = "API_ADDRESS_DATA_FAILED";

export const API_PERSON_DATA_REQUEST = "API_PERSON_DATA_REQUEST";
export const API_PERSON_DATA_SUCCESS = "API_PERSON_DATA_SUCCESS";
export const API_PERSON_DATA_FAILED = "API_PERSON_DATA_FAILED";