export const courses = [
    "Administração",
    "Ciência da Computação",
    "Ciências Atmosféricas",
    "Ciências Biológicas Licenciatura",
    "Engenharia Ambiental",
    "Engenharia Civil",
    "Engenharia de Bioprocessos",
    "Engenharia de Computação",
    "Engenharia de Controle e Automação",
    "Engenharia de Energia",
    "Engenharia de Materiais",
    "Engenharia de Produção",
    "Engenharia Elétrica",
    "Engenharia Eletrônica",
    "Engenharia Hídrica",
    "Engenharia Mecânica",
    "Engenharia Mecânica Aeronáutica",
    "Engenharia Química",
    "Física Bacharelado",
    "Física Licenciatura",
    "Matemática Bacharelado",
    "Matemática Licenciatura",
    "Química Bacharelado",
    "Química Licenciatura",
    "Sistemas de Informação"
]